In [1]:
import pandas as pd

dataframe = pd.read_csv("Datasets/dataset_large.csv")
dataframe.head()
#dataframe.info()
#dataframe.describe()
print(dataframe)

         ID  Edad       Ciudad  Puntaje  Ingreso
0         1    56       Toluca       78    33234
1         2    46  Guadalajara       73    24786
2         3    32         CDMX       87    42100
3         4    60       Toluca       61    20329
4         5    25         CDMX       78    20698
...     ...   ...          ...      ...      ...
9995   9996    33  Guadalajara       82    45836
9996   9997    29         CDMX       78     6284
9997   9998    18         CDMX       86    33094
9998   9999    25         CDMX       71    19466
9999  10000    30       Toluca       75    43121

[10000 rows x 5 columns]


In [2]:
first_row = dataframe.iloc[200]
print("First row:", first_row)  #sample with features

#columns per label
col_city = dataframe['Ciudad']
print(col_city)

First row: ID           201
Edad          56
Ciudad      CDMX
Puntaje       83
Ingreso    32158
Name: 200, dtype: object
0            Toluca
1       Guadalajara
2              CDMX
3            Toluca
4              CDMX
           ...     
9995    Guadalajara
9996           CDMX
9997           CDMX
9998           CDMX
9999         Toluca
Name: Ciudad, Length: 10000, dtype: object


In [3]:
# samples ('Edad')> 50
mayores_50 = dataframe[dataframe["Edad"] > 50]
print(mayores_50)
print(type(mayores_50))

        ID  Edad       Ciudad  Puntaje  Ingreso
0        1    56       Toluca       78    33234
3        4    60       Toluca       61    20329
6        7    56    Monterrey       85    21548
12      13    53       Toluca       97    39536
13      14    57         CDMX       82    36755
...    ...   ...          ...      ...      ...
9973  9974    54  Guadalajara       95    36723
9976  9977    53       Puebla       83    45043
9984  9985    51         CDMX       62    23645
9985  9986    60  Guadalajara       53     6023
9994  9995    59    Monterrey       77    25141

[2982 rows x 5 columns]
<class 'pandas.core.frame.DataFrame'>


In [4]:
#convert pandas -> numpy
#in ML many models receive Numpy "ndarray"
#scalars
#vectors
#matrix
#tensors

import numpy as np

'''
Select only the relevant numeric colums (here all are)
Puntaje, Edad, Ingreso
'''

num_vec = dataframe.select_dtypes(include=["number"]) .to_numpy()#float and integer

#select_dtypes -> filtering
#.to_numpy -> convert

print(num_vec)
print(type(num_vec))
print("Shape:", num_vec.shape)
print(num_vec[9999])

[[    1    56    78 33234]
 [    2    46    73 24786]
 [    3    32    87 42100]
 ...
 [ 9998    18    86 33094]
 [ 9999    25    71 19466]
 [10000    30    75 43121]]
<class 'numpy.ndarray'>
Shape: (10000, 4)
[10000    30    75 43121]


In [5]:

#steps to calculating cos(theta)

# 1) norm of each rows (lenght of each vector (each vector is a row))

print("Norms")
norms = np.linalg.norm(num_vec, axis=1) #axis --> 0 by column, 1 by row
print(norms,"\n")

# 2) dot product of each tuple (row, row)

print("Dot product")
dot_product = num_vec @ num_vec.T #.ndot np.dot "@" works always
print(dot_product, "\n")

#Calculation of cos(theta)
#difference of each sample (not minus (-)) features

norms = norms.reshape(-1, 1)
print(norms, "\n")#print like a lits

cosine_matrix = dot_product / (norms @ norms.T)
print("Cosine \n", cosine_matrix [999,9987]) #difference between 999  and 9987 (features)


Norms
[33234.13872812 24786.15026582 42100.1021614  ... 34571.38354188
 21884.03123284 44265.41726901] 

Dot product
[[1104507977  823746196 1399159981 ... 1099863710  646949981 1433100844]
 [ 823746196  614353245 1043498429 ...  820294986  482510607 1068823961]
 [1399159981 1043498429 1772418602 ... 1393295452  819555574 1815431585]
 ...
 [1099863710  820294986 1393295452 ... 1195180560  744184362 1527033364]
 [ 646949981  482510607  819555574 ...  744184362  478910823  939389461]
 [1433100844 1068823961 1815431585 ... 1527033364  939389461 1959427166]] 

[[33234.13872812]
 [24786.15026582]
 [42100.1021614 ]
 ...
 [34571.38354188]
 [21884.03123284]
 [44265.41726901]] 

Cosine 
 0.9799218617449923
