In [43]:
from random import Random

import pandas as pd
from sklearn.datasets import load_iris  #example dataset (flowers)
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split  #split arrays/data into train/validation/test set
from sklearn.preprocessing import StandardScaler  #standarize features (mean =0, variance =1)
from sklearn.pipeline import Pipeline  #chain process (train-validation-test)
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [44]:
iris = load_iris()
#print(iris)
#print(type(iris))
print("Target", iris.target)  #labes (king of flowers)
print("Features names", iris.feature_names)
print("Target names", iris.target_names)

Target [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
Features names ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Target names ['setosa' 'versicolor' 'virginica']


In [45]:
import pandas as pd  #convert from bunch (objet) to pandas DataFrame

x = iris.data  #features
y = iris.target  #labels

feature_names = iris.feature_names
df = pd.DataFrame(x, columns=iris.feature_names)
df['target'] = y
print(df)

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  

In [46]:
x_train, x_temp, y_train, y_temp = train_test_split(  # x_temp and y_temp are 30%
    x,  # features, can be numpy array o pandas dataframe
    y,  #labels (optionals)
    test_size=0.3,  #proportion of the dataset reserved for temporary
    random_state=42,  #random (seed)
    #ensure the reproducibility, every time you run the code
    stratify=y  #ensures each class proportion are preserved
)
#data (samples, labels) 0.3 (%70 test)


#split 15% for validation 15% for test
x_val, x_test, y_val, y_test = train_test_split(
    x_temp,  # features, can be numpy array o pandas dataframe
    y_temp,  #labels (optionals)
    test_size=0.5,  #proportion of the dataset reserved for temporary
    random_state=42,  #random (seed)
    #ensure the reproducibility, every time you run the code
    stratify=y_temp  #ensures each class proportion are preserved
)

#data (samples,labels), 0.5 validation 0.5 test

print("Lenght Iris", len(y))
print("Train x", x_train.shape, "y", y_train.shape, "whit ", len(y_train) / len(y) * 100, "%")
print("Validation x ", x_val.shape, "y", y_val.shape, "whit ", len(y_val) / len(y) * 100, "%")
print("Test x", x_test.shape, "y", y_test.shape, "whit ", len(y_test) / len(y) * 100, "%")

#accuracy = exactitud
#precision = precision porcentaje de los predecidos como verdadero de todos los positivos

Lenght Iris 150
Train x (105, 4) y (105,) whit  70.0 %
Validation x  (22, 4) y (22,) whit  14.666666666666666 %
Test x (23, 4) y (23,) whit  15.333333333333332 %


In [47]:
pipe = Pipeline([

    #1 preprocessing
    #StandardScaler (normalizar -> media 0 y varianza 1)
    ("scaler", StandardScaler()),

    #2 model (logistic regression)

    ("clf", LogisticRegression(  #hyperparameters
        C=1.0,  #control the force of regulation and the overfitting (falta de entrenamiento)
        random_state=42,
        max_iter=1000,  #iteration numbers
        multi_class="auto",  #strategy for multiclass classification
    ))  #clf clasificador
])

In [48]:
#step 1 fit the pipeline on the train data
pipe.fit(x_train, y_train)  #standardScaler -> LogisticRegression
#standardScaler.train()
#standarScaler.predict()
#logisticRegression.train()
#logisticRegression.predict()
#computes the preprocessing and model

#step 2
# train the pipeline on the validation data
y_val_predict = pipe.predict(x_val)
print(y_val)
print(y_val_predict)

#step 3
#compute accuracy on the validation set
val_acc = accuracy_score(y_val, y_val_predict)
print("Validation Accuracy", val_acc)
cm1 = confusion_matrix(y_val, y_val_predict)
print(cm1)

#step 4
y_test_pred = pipe.predict(x_test)  #evaluate on test set
test_acc = accuracy_score(y_test, y_test_pred)
print("Test Accuracy", test_acc)

cm2 = confusion_matrix(y_test, y_test_pred)
print(cm2)

[1 2 1 2 2 1 0 0 0 0 2 1 2 0 0 1 2 1 0 2 0 1]
[2 2 1 1 2 1 0 0 0 0 1 1 2 0 0 1 2 1 0 2 0 1]
Validation Accuracy 0.8636363636363636
[[8 0 0]
 [0 6 1]
 [0 2 5]]
Test Accuracy 0.9565217391304348
[[7 0 0]
 [0 8 0]
 [0 1 7]]


C:\Users\pacom\OneDrive\Escritorio\Temas Selectos I\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1272: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
