In [1]:
import scipy, pandas, numpy, statsmodels, matplotlib, sklearn, networkx

print("Scipy" , scipy.__version__)
print("Mumpy",numpy.__version__)
print("Pandas", pandas.__version__)
print("Stats", statsmodels.__version__)
print("matplotlib", matplotlib.__version__)
print("sklearn", sklearn.__version__)
print("Networkx", networkx.h__version__)

Scipy 1.16.1
Mumpy 2.3.2
Pandas 2.3.1
Stats 0.14.5
matplotlib 3.10.5
sklearn 1.7.1
Networkx 3.5


In [2]:
import numpy as np

x= np.array([[1.2, 3.1, 0.5],
             [0.9, 2.4, 1.4],
             [2.2, 0.4, 3.3]]) #numpy array works only with numbers but can show other data types

print(x)

[[1.2 3.1 0.5]
 [0.9 2.4 1.4]
 [2.2 0.4 3.3]]


In [3]:
x.shape #forma de la matrix "size"

(3, 3)

In [4]:
print(x[1]) #print the second row (sample)
print(x[:,1]) #print the second colum (feature)

[0.9 2.4 1.4]
[3.1 2.4 0.4]


In [5]:
import pandas as pd

data = { #key:value
         #key is sample
         #value(s) are the features
         'Weight': [150, 249, 1000, 350],
         'Brand': ["DJI","Insta", "Canon", "Chinito"],
         'Speed': [30,50, 120, 150],
         "Color": ["Gray", "Black", "White", "Orange"]

}
print(data) #print dictionary
df = pd.DataFrame(data) # primero trabajamos con diccionarios y despues con tablas
print(df)

{'Weight': [150, 249, 1000, 350], 'Brand': ['DJI', 'Insta', 'Canon', 'Chinito'], 'Speed': [30, 50, 120, 150], 'Color': ['Gray', 'Black', 'White', 'Orange']}
   Weight    Brand  Speed   Color
0     150      DJI     30    Gray
1     249    Insta     50   Black
2    1000    Canon    120   White
3     350  Chinito    150  Orange


In [6]:
df.info () #data types
df.describe() #basic calculations (statistics)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Weight  4 non-null      int64 
 1   Brand   4 non-null      object
 2   Speed   4 non-null      int64 
 3   Color   4 non-null      object
dtypes: int64(2), object(2)
memory usage: 260.0+ bytes


Weight       Speed
count     4.000000    4.000000
mean    437.250000   87.500000
std     383.949107   56.789083
min     150.000000   30.000000
25%     224.250000   45.000000
50%     299.500000   85.000000
75%     512.500000  127.500000
max    1000.000000  150.000000